swagger: "2.0"
info:
  title: LangBridge API
  description: API for LangBridge chat functions
  version: "1.0.0"
schemes:
  - https
produces:
  - application/json
paths:
  /api/talk:
    post:
      summary: Talk stream endpoint
      operationId: talkStream
      x-google-backend:
        address: ${TALK_STREAM}
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              askText:
                type: string
              sessionId:
                type: string
              traceId:
                type: string
              extra:
                type: object
      responses:
        200:
          description: Successful response
  /api/welcome:
    post:
      summary: Welcome message endpoint
      operationId: welcome
      x-google-backend:
        address: ${WELCOME}
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              traceId:
                type: string
              sessionId:
                type: string
              languageCode:
                type: string
      responses:
        200:
          description: Successful response
  /api/goodbye:
    post:
      summary: Goodbye message endpoint
      operationId: goodbye
      x-google-backend:
        address: ${GOODBYE}
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              traceId:
                type: string
              sessionId:
                type: string
              languageCode:
                type: string
      responses:
        200:
          description: Successful response
  /api/recquestions:
    post:
      summary: Recommended questions endpoint
      operationId: recquestions
      x-google-backend:
        address: ${RECQUESTIONS}
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              traceId:
                type: string
              languageCode:
                type: string
      responses:
        200:
          description: Successful response
  /api/speech:
    post:
      summary: Speech message endpoint
      operationId: speech
      x-google-backend:
        address: ${SPEECH}
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              traceId:
                type: string
              sessionId:
                type: string
              languageCode:
                type: string
      responses:
        200:
          description: Successful response
  /api/config:
    post:
      summary: Configuration endpoint
      operationId: config
      security:
        - api_key: []
      x-google-backend:
        address: ${CONFIG}
      parameters:
        - in: body
          name: body
          required: true
          schema:
            type: object
            properties:
              welcome_messages:
                type: object
              goodbye_messages:
                type: object
              recommended_questions:
                type: object
      responses:
        200:
          description: Successful response
securityDefinitions:
  api_key:
    type: apiKey
    name: key
    in: query
