import argparse
import json
import logging
import os
import sys
import time
import requests
from pptx import Presentation
from google.cloud import storage

# Add backend root to sys.path to allow imports
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Import admin tool for creating the course
from admin_tools.manage_courses import create_or_update_course

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# --- HELPERS ---

def load_cdktf_outputs():
    """
    Loads backend/cdktf_outputs.json to get infrastructure details.
    """
    output_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "cdktf_outputs.json"
    )
    
    if not os.path.exists(output_path):
        return {}
        
    try:
        with open(output_path, 'r') as f:
            return json.load(f)
    except Exception as e:
        logger.warning(f"Failed to read cdktf_outputs.json: {e}")
        return {}

def load_credentials():
    """
    Attempts to load the API key from backend/admin_tools/api_key.json.
    Returns the key string or None if not found/valid.
    """
    key_path = os.path.join(
        os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
        "admin_tools",
        "api_key.json"
    )
    
    if not os.path.exists(key_path):
        return None
        
    try:
        with open(key_path, 'r') as f:
            data = json.load(f)
            # Support the format generated by create_api_key.py or simple {"api_key": "..."}
            return data.get("key_string") or data.get("api_key")
    except Exception as e:
        logger.warning(f"Failed to read api_key.json: {e}")
        return None

def upload_to_bucket(bucket_name, source_file_path, destination_blob_name):
    """
    Uploads a file to the bucket and returns the public URL.
    """
    try:
        storage_client = storage.Client()
        bucket = storage_client.bucket(bucket_name)
        blob = bucket.blob(destination_blob_name)

        blob.upload_from_filename(source_file_path)
        
        # Construct public URL (assuming the bucket allows public access or we use the media link)
        # For private buckets, we might need a signed URL, but here we'll try the public media link style
        # or the storage.googleapis.com style if the object is public.
        # Given the requirement "send the slide url", and this is likely for a demo/dev environment:
        
        # Attempt to make it public (optional, depending on bucket settings)
        # blob.make_public() 
        
        url = blob.public_url
        logger.info(f"✅ Uploaded {source_file_path} to {destination_blob_name}. URL: {url}")
        return url
    except Exception as e:
        logger.error(f"❌ Failed to upload {source_file_path} to bucket: {e}")
        return None

# --- DEMO DATA ---

DEMO_COURSE_ID = "physics-101-demo"
DEMO_COURSE_TITLE = "Introduction to Physics: Motion and Forces"
DEMO_LANGUAGES = ["en-US", "zh-CN", "yue-HK"]

# Mapping for visual folder suffixes
LANG_VISUAL_SUFFIX_MAP = {
    "en-US": "en",
    "zh-CN": "zh-CN",
    "yue-HK": "yue-HK"
}

LECTURE_1_PPT_FILENAME = "Physics_101_Lecture_1.pptx"
LECTURE_1_SLIDES = [
    {
        "slide_number": "1",
        "speaker_notes": "Welcome everyone to Physics 101. Today we are going to talk about the fundamental laws of motion. Specifically, we will look at Newton's Three Laws of Motion and how they govern the world around us."
    },
    {
        "slide_number": "2",
        "speaker_notes": "First, let's define 'Force'. A force is simply a push or a pull upon an object resulting from the object's interaction with another object. Whenever there is an interaction between two objects, there is a force upon each of the objects."
    },
    {
        "slide_number": "3",
        "speaker_notes": "Newton's First Law, also known as the Law of Inertia, states that an object at rest stays at rest and an object in motion stays in motion with the same speed and in the same direction unless acted upon by an unbalanced force."
    },
    {
        "slide_number": "4",
        "speaker_notes": "Newton's Second Law provides the calculation for force. It states that Force equals mass times acceleration. F equals m a. This means that the heavier an object is, the more force is needed to move it."
    },
    {
        "slide_number": "5",
        "speaker_notes": "Finally, Newton's Third Law: For every action, there is an equal and opposite reaction. This means that in every interaction, there is a pair of forces acting on the two interacting objects."
    },
    {
        "slide_number": "6",
        "speaker_notes": "That concludes our brief introduction. Please review Chapter 1 in your textbooks for next week's lab session. Thank you for listening!"
    }
]

LECTURE_2_PPT_FILENAME = "Physics_101_Lecture_2.pptx"
LECTURE_2_SLIDES = [
    {
        "slide_number": "1",
        "speaker_notes": "Good morning class! In our previous lecture, we covered Newton's Laws of Motion. Today, we will expand on these concepts by introducing work, energy, and power. These concepts are crucial for understanding how forces affect objects over distances and time."
    },
    {
        "slide_number": "2",
        "speaker_notes": "Work, in physics, is defined as a force causing displacement. A force does work on an object if it causes a displacement of the object. The amount of work done is calculated as Force times Distance, specifically the component of force in the direction of displacement."
    },
    {
        "slide_number": "3",
        "speaker_notes": "Energy is the capacity to do work. There are various forms of energy, such as kinetic energy (energy of motion) and potential energy (stored energy). The Law of Conservation of Energy states that energy cannot be created or destroyed, only transformed from one form to another."
    },
    {
        "slide_number": "4",
        "speaker_notes": "Kinetic energy is the energy an object possesses due to its motion. It is directly proportional to the mass of the object and the square of its velocity. So, a faster or heavier object has more kinetic energy."
    },
    {
        "slide_number": "5",
        "speaker_notes": "Potential energy is stored energy. Gravitational potential energy depends on an object's mass, height, and the acceleration due to gravity. Elastic potential energy is stored in stretched or compressed elastic materials."
    },
    {
        "slide_number": "6",
        "speaker_notes": "Finally, power is the rate at which work is done or energy is transferred. It tells us how quickly work is performed. Power is calculated as Work divided by Time, or Force times Velocity. This concludes our lecture on work, energy, and power. Please prepare for a short quiz next session."
    }
]

# -----------------

def generate_pptx(filename, slides_data):
    """Generates a dummy PPTX file with speaker notes."""
    prs = Presentation()
    
    # Use 'Title Only' layout (index 5) which definitely has a title placeholder
    slide_layout = prs.slide_layouts[5] 
    
    for slide_info in slides_data:
        slide = prs.slides.add_slide(slide_layout)
        
        # Set title
        if slide.shapes.title:
            slide.shapes.title.text = f"Slide {slide_info['slide_number']}"
        
        # Add notes
        notes_slide = slide.notes_slide
        text_frame = notes_slide.notes_text_frame
        text_frame.text = slide_info['speaker_notes']
        
    # Ensure seeds directory exists
    seeds_dir = os.path.dirname(os.path.abspath(__file__))
    file_path = os.path.join(seeds_dir, filename)
    
    prs.save(file_path)
    logger.info(f"✅ Generated PPTX: {file_path}")
    return file_path

def create_demo_course():
    """Creates the demo course in Firestore using admin tools."""
    logger.info(f"Creating demo course: {DEMO_COURSE_ID}...")
    
    voice_configs = {
        "en-US": {"name": "en-US-Neural2-F", "gender": "FEMALE"},
        "zh-CN": {"name": "cmn-CN-Chirp3-HD-Achernar", "gender": "FEMALE"},
        "yue-HK": {"name": "yue-HK-Standard-A", "gender": "FEMALE"}
    }
    
    try:
        create_or_update_course(
            DEMO_COURSE_ID, 
            DEMO_COURSE_TITLE, 
            DEMO_LANGUAGES, 
            voice_configs
        )
        logger.info("✅ Course created successfully.")
    except Exception as e:
        logger.error(f"❌ Failed to create course: {e}")
        sys.exit(1)

def simulate_presentation(api_url, api_key, slides_data, ppt_filename, bucket_name=None):
    """Simulates a live presentation by sending requests to the API."""
    logger.info(f"Starting simulation for {len(slides_data)} slides from {ppt_filename}...")
    logger.info(f"Target API: {api_url}")
    
    # Append API key to URL if provided
    url = api_url
    if api_key:
        if "?" in url:
            url += f"&key={api_key}"
        else:
            url += f"?key={api_key}"

    # Determine visuals directory
    seeds_dir = os.path.dirname(os.path.abspath(__file__))
    ppt_basename = os.path.splitext(ppt_filename)[0]
    # Assuming 'en' visuals for the simulation
    visuals_dir = os.path.join(seeds_dir, "generate", f"{ppt_basename}_en_visuals")

    for slide in slides_data:
        slide_num = slide["slide_number"]
        notes = slide["speaker_notes"]
        
        logger.info(f"\n--- Processing {ppt_filename}, Slide {slide_num} ---")
        logger.info(f"Notes: {notes[:60]}...")
        
        payload = {
            "generate_presentation": True,
            "courseId": DEMO_COURSE_ID,
            "context": notes,
            "ppt_filename": ppt_filename,
            "page_number": slide_num
        }

        language_specific_slide_links = {}
        if bucket_name:
            for lang_code, suffix in LANG_VISUAL_SUFFIX_MAP.items():
                visuals_dir = os.path.join(seeds_dir, "generate", f"{ppt_basename}_{suffix}_visuals")
                image_filename = f"slide_{slide_num}_reimagined.png"
                image_path = os.path.join(visuals_dir, image_filename)
                
                if os.path.exists(image_path):
                    logger.info(f"Found visual for {lang_code}: {image_filename}. Uploading to bucket...")
                    blob_name = f"generated_visuals/{ppt_basename}/{lang_code}/{image_filename}" # Include lang_code in blob path
                    
                    image_url = upload_to_bucket(bucket_name, image_path, blob_name)
                    if image_url:
                        language_specific_slide_links[lang_code] = image_url
                        logger.info(f"Added slide_link for {lang_code}: {image_url}")
                else:
                    logger.warning(f"Visual image not found for {lang_code} at {image_path}")
        
        if language_specific_slide_links:
            payload["language_specific_slide_links"] = language_specific_slide_links

        try:
            start_time = time.time()
            response = requests.post(url, json=payload)
            duration = time.time() - start_time
            
            if response.status_code == 200:
                logger.info(f"✅ API Success ({duration:.2f}s)")
            else:
                logger.error(f"❌ API Error {response.status_code}: {response.text}")
        except Exception as e:
            logger.error(f"❌ Request Failed: {e}")
            
        # Wait a bit between slides to simulate real pacing, or just to let logs settle
        logger.info("Waiting 2 seconds before next slide...")
        time.sleep(2)

    logger.info(f"\n✅ Simulation for {ppt_filename} complete!")

def main():
    parser = argparse.ArgumentParser(description="Seed Demo Class and Simulate Presentation")
    parser.add_argument("--api-url", help="Base URL of the Config Cloud Function")
    parser.add_argument("--api-key", help="API Key for the gateway")
    parser.add_argument("--skip-create", action="store_true", help="Skip creating the course (simulation only)")
    
    args = parser.parse_args()
    
    # Resolve defaults
    file_api_key = load_credentials()
    final_api_key = args.api_key or file_api_key
    
    final_api_url = args.api_url
    bucket_name = None
    
    # Try to load from cdktf_outputs.json
    outputs = load_cdktf_outputs()
    
    # Check if outputs are nested under "cdktf" or similar
    cdktf_outputs = outputs.get("cdktf", outputs)
    
    if not final_api_url:
        base_url = cdktf_outputs.get("api-url")
        if base_url:
            # Remove trailing slash
            if base_url.endswith("/"):
                base_url = base_url[:-1]
            
            # Construct full config endpoint
            final_api_url = f"https://{base_url}/api/config"
    
    bucket_name = cdktf_outputs.get("speech-file-bucket")
    if bucket_name:
        logger.info(f"Found speech bucket: {bucket_name}")
    else:
        logger.warning("⚠️ Speech bucket not found in cdktf_outputs.json")

    if not final_api_url:
        logger.error("❌ API URL is required. Provide --api-url or ensure backend/cdktf_outputs.json exists and has 'api-url'.")
        sys.exit(1)
        
    if not final_api_key:
        logger.warning("⚠️ No API Key provided or found. Request may fail if Gateway is secured.")

    if not args.skip_create:
        create_demo_course()
    else:
        logger.info("Skipping course creation as requested.")
        
    # Generate PPTX files
    # generate_pptx(LECTURE_1_PPT_FILENAME, LECTURE_1_SLIDES)
    # generate_pptx(LECTURE_2_PPT_FILENAME, LECTURE_2_SLIDES)
        
    simulate_presentation(final_api_url, final_api_key, LECTURE_1_SLIDES, LECTURE_1_PPT_FILENAME, bucket_name)
    logger.info("\n--- Starting Second Lecture ---")
    time.sleep(5) # Pause between lectures
    simulate_presentation(final_api_url, final_api_key, LECTURE_2_SLIDES, LECTURE_2_PPT_FILENAME, bucket_name)

if __name__ == "__main__":
    main()
